- name: Deploy Finance Project
  hosts: test_servers
  become: true
  tasks:
    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: faiyazluck/finance-me-service:latest
        source: pull
        force_source: yes  # Ensures it always pulls the latest image

    - name: Stop and remove old container (if exists)
      community.docker.docker_container:
        name: finance-service
        state: absent  # Ensures the container is removed if it exists

    - name: Run the new container
      community.docker.docker_container:
        name: finance-service
        image: faiyazluck/finance-me-service:latest
        state: started
        restart_policy: always
        ports:
          - "80:8080"
