- name: Deploy Finance Project
  hosts: test
  become: true
  tasks:
    # ----------- Pull and Run Finance Service in Docker ----------- #
    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: faiyazluck/finance-me-service:latest
        source: pull
        force_source: yes

    - name: Stop and remove old container (if exists)
      community.docker.docker_container:
        name: finance-service
        state: absent  # Ensures the container is removed if it exists

    - name: Run the new container
      community.docker.docker_container:
        name: finance-service
        image: faiyazluck/finance-me-service:latest
        state: started
        restart_policy: always
        ports:
          - "80:8080"

    # ----------- Install Prometheus ----------- #
    - name: Set Prometheus download URL
      set_fact:
        prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v2.53.4/prometheus-2.53.4.linux-amd64.tar.gz"

    - name: Download Prometheus
      get_url:
        url: "{{ prometheus_download_url }}"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /opt/prometheus-2.53.4.linux-amd64/prometheus /usr/local/bin/

    - name: Find Prometheus config file
      shell: "find /opt -type f -name 'prometheus.yml'"
      register: prometheus_config_path

    - name: Move Prometheus config
      command: mv {{ prometheus_config_path.stdout }} /etc/prometheus.yml

    - name: Ensure Prometheus data directory exists
      file:
        path: /var/lib/prometheus
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create Prometheus service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Prometheus service
      systemd:
        daemon_reload: yes
        name: prometheus
        enabled: yes
        state: started

    # ----------- Install Grafana ----------- #
    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
